final List<String> expenseList=[
                                    "ABEL",
                                    "AGRI LOAN",
                                    "AUTO CHARGE",
                                    "BANK CHARGES",
                                    "CHITTY",
                                    "CONSTRUCTION",
                                    "COURIER CHARGES",
                                    "DONATION",
                                    "DRIVER ALLOWANCE",
                                    "DTDC",
                                    "EMI",
                                    "FARM EXPENSES",
                                    "FOOD EXPENSE",
                                    "GAS",
                                    "GAS PURCHASE",
                                    "HEALTH INSURANCE",
                                    "HOUSE RENT",
                                    "IMPORT EXPORT LICENSE",
                                    "INTERNET",
                                    "JEETHO DIESEL CREDIT BILL",
                                    "JEETHO EXPENSES",
                                    "JEETHO PLUS",
                                    "KSEB DEPOSIT",
                                    "OFFICE EXPENSES",
                                    "PETROL-OFFICE",
                                    "PRINTING EXPENSE",
                                    "PURCHASE WITHOUT GST",
                                    "SALARY",
                                    "SALARY ADVANCES",
                                    "SALARY-BENGALIS",
                                    "SALARY IN ADVANCE BENGALIS",
                                    "SERVICE AND REPAIR",
                                    "SNACKS",
                                    "TRANSPORTATION",
                                    "WAGANOR PETROL",
                                    "ECP TRADING",
                                    "NEOPOLY PACK",
                                    "DIO FUELS TEEKOY",
                                    "MATHA SURGICALS",
                                    "PHARM O SALES",
                                    "K & T AGROW MILLS PVT LTD",
                                    "ASSOCIATED RUBBER CHEMICALS",
                                    "BRMSCO",
                                    "NORTHMAPS GLOBAL ECOSOLUTIONS PVT LTD",
                                    "AGROWTEIN",
                                    "KINDLEARC SEVEN",
                                    "LOGIN IT SOLUTIONS",
                                    "KAIRALI STOREWALLS",
                                    "BERITE SOLUTIONS",
                                    "DIO FUELS",
                                    "ASIAN GLASS & PLYWOODS",
                                    "SHALIMAR TRADE LINKS",
                                    "BIZZARO UNIFORMS",
                                  ];

final List<String> incomeList= [
                                    " BED",
                                    "CALCIUM CARBONATE",
                                    "CLING WRAP FILM",
                                    "DRY MUSHROOM",
                                    "EAT IN TRAY",
                                    "FARM CONSULTANCY",
                                    "MUSHROOM SPAWN",
                                    "P P COVER",
                                    "PELLET SACK",
                                    "TAPE",
                                    "TRAINING FEE",
                                    "VARIETY MUSHROOM SPAWN"
                                  ];